spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb_test
spring.datasource.username=postgres
spring.datasource.password=5656
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Disable SQL logs in tests (optional)
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=ERROR
